### ISSUE TITLE
Automation script isn't always deployed on 1st try

### ISSUE THREAD

**Issue by rviera01** [sharptree/vscode-autoscript-deploy#12]
1st I want to say I absolutely love this tool for VS Code.  It makes my life so much easier in develop automation scripts for our environment.  Thank you.

After the most recent update I began noticing that my updates to an automation script were not always deployed on the first attempt, so I began a practice of deploying 2 or even 3 times to be sure that my testing isn't complicated by a non-deploy.

Thank you again for a great tool.

**Comment by jvenhuizen** [comment]
If you have any additional information that would be very helpful. One thing I have noticed is that in clustered environments it may take a moment for the script to propagate to all members in the cluster, in which case it may appear that the script has not been applied.  

If there are any error messages or details you can provide that would be appreciated.

**Comment by rviera01** [comment]
That sounds very reasonable.  I'll be more patient when posting updated code and see if the problem subsides.  Is there way for me to tell that it's been posted to all members?

**Comment by jvenhuizen** [comment]
I am not aware of any place in the front end that you can view the propagation progress although you will see an entry in the MAXSESSION table in the RELOADCACHE attribute, which would indicate if it has been processed.

Unrelated, but since you are already using the VS Code plugin you may be interested in how it ties into deployment pipelines, in case you didn't see this: https://www.sharptree.io/blog/2023/2023-11-07-devops-deploy/

**Comment by rviera01** [comment]
Thank you very much for the information.
