### ISSUE TITLE
PARSE ERROR

### ISSUE THREAD

**Issue by 0v3rd0s33** [sharptree/vscode-autoscript-deploy#13]
When i try to access first time i have error: parse error: Expected HTTP/
First he ask me a pass
![image](https://github.com/sharptree/vscode-autoscript-deploy/assets/73673294/f5f825ce-6536-462b-a11b-3e8d4f911f88)

I put it and have error
![image](https://github.com/sharptree/vscode-autoscript-deploy/assets/73673294/7e13466a-d7b5-4110-a800-f91d1cc5ec10)

**Comment by jvenhuizen** [comment]
The error you are seeing typically is because you have entered an invalid host name or are trying to access a non-ssl instance with SSL enabled.  Note also that the hostname should only be the host name and not include the http:// or a trailing slash.

It is on our enhancement list to provide better host name validation and error messages.

**Comment by jvenhuizen** [comment]
Closing the issue for lack of response.  If the error continues or you have more information please feel free to re-open it.
