### ISSUE TITLE
Extract only 1 script? instead of all 

### ISSUE THREAD

**Issue by abdulqadeerel** [sharptree/vscode-autoscript-deploy#5]
How can i extract only 1 selected script? instead of extrating all again n again.

**Comment by jvenhuizen** [comment]
Currently it is not possible to extract a single script.  The UI available in for the VS Code extension does not provide a nice way to dynamically provide a selection list and asking a user to manually enter the script name did not seem an attractive alternative.

Furthermore the extraction process is intended to be a one time event that enables a developer to baseline their version control repository (typically Git) and then use that as the definitive script version going forward.  Effectively, you should never need to manually edit a script in Maximo after the initial export.

However if you do need to extract scripts multiple times the extract process does compare the script hash values and only updates the scripts that have changed since the last export.

All that said, I will add a feature request and aim to enable single script extraction in the next feature release.

**Comment by jvenhuizen** [comment]
As it turns out there is a a QuickPick control now available which lets us provide a searchable list so you can select a single script / screen / inspection form. This is now available in version 1.11 (June 9th 2023).
